dist: trusty
language: java

jdk:
- openjdk11
addons:
  sonarcloud:
    organization: "chiacchius"
    token:
      secure: "AJbIrl5oDNrLNtjCt7JIFKoQndrSrX8+gd8p1ug5CmFrHlLKPg8//x3+nPVN1TeP1I1gT0g0Bz89ahtDuxfuqJ7mUdXWGlmghZ/d8i2wQYZBy9QAeL60aV+QRDWQXkbQBj5zR+QMSqUYZwpZCbmK0qxZcDKUKj3W4IvVHySuDSiv1YahVUwPK66sRgwiTOt90cedjLIACW//0i0qU0WX7ViQEt/Z08uiWU6UO8gAK+ExllTWO7hgnxjb5eF+5Ljrj4/2HBrJv6nVvoBb5P5zcob0jKDfsoYIhoSuZNCc51mrsn5icHf6gHH3Ptbo9l2vIJOjjTxpwJqD4ZtWhlOU0FzELlSf12Pnf5f39HKvH6Y9PUde8N/8F2H6EfIu73BEmw1bqEPZ2g0SUeyIiZjXNQ22enGmLSwTlME5yVxzfax7CqvhfmDOT2D1E1I0JdJpFpN7cu3NIePetoBS7v3qzQgto5AAbFIhT6x1IXc8Lm6M3q5ZMb6a7Dv4BV8KYuBFbpKFtuY7O7c/ezy4uJdAkJBT0ATmg8cpB9gUsNA6uXK16EuuRFwWb7hdC3u3AE39LBYq+0+wbsZudI88Oj0akfHksKrUvvXiho4h06FH6i70+iFe+x5J4awGnB9acGzHcqSIm/1bvsVqDTPjzGNkg0pTgQ/yhDGK8h5fyWuB1yM=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Dsonar.login=e315a538d90e4318286f0c91d9aeda71e02c1e7e
